import { useMemo, useState } from "react";
import { Calculator, Percent, Receipt, CalendarDays, Ruler, Scale, TrendingUp } from "lucide-react";
import { useI18n } from "@/i18n/I18nContext";

type CalcMode = "basic"|"percent"|"discount"|"vat"|"date"|"unit"|"ratio"|"change"|"margin"|"loan"|"installment"|"time";

export default function CompoundCalculator() {
  const { language } = useI18n(); const ko=language==="ko";
  const [mode,setMode]=useState<CalcMode>("basic");
  const [a,setA]=useState(""); const [b,setB]=useState(""); const [op,setOp]=useState("+");
  const [percent,setPercent]=useState(""); const [price,setPrice]=useState(""); const [vatRate,setVatRate]=useState("10");
  const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [inclusive,setInclusive]=useState(false);
  const [unitValue,setUnitValue]=useState(""); const [unitCategory,setUnitCategory]=useState("length"); const [unit,setUnit]=useState("m");
  const [ratioA,setRatioA]=useState(""); const [ratioB,setRatioB]=useState(""); const [ratioC,setRatioC]=useState("");
  const [before,setBefore]=useState(""); const [after,setAfter]=useState("");
  const [cost,setCost]=useState(""); const [sale,setSale]=useState("");
  const [loan,setLoan]=useState(""); const [loanRate,setLoanRate]=useState("4"); const [loanYears,setLoanYears]=useState("1");
  const [installment,setInstallment]=useState(""); const [installmentRate,setInstallmentRate]=useState("4"); const [installmentMonths,setInstallmentMonths]=useState("12");
  const [timeStart,setTimeStart]=useState(""); const [timeEnd,setTimeEnd]=useState(""); const [breakMinutes,setBreakMinutes]=useState("0");

  const basic=useMemo(()=>{const x=Number(a),y=Number(b);if(!a||!b||!Number.isFinite(x)||!Number.isFinite(y))return "";if(op==="÷"&&y===0)return ko?"0으로 나눌 수 없습니다.":"Cannot divide by zero.";const v=op==="+"?x+y:op==="-"?x-y:op==="×"?x*y:op==="%"?x%y:op==="^"?x**y:x/y;return v.toLocaleString(undefined,{maximumFractionDigits:10})},[a,b,op,ko]);
  const percentResult=useMemo(()=>{const x=Number(a),p=Number(percent);return !a||!percent||!Number.isFinite(x)||!Number.isFinite(p)?"":(x*p/100).toLocaleString(undefined,{maximumFractionDigits:10})},[a,percent]);
  const discount=useMemo(()=>{const x=Number(price),p=Number(percent);if(!price||!percent||!Number.isFinite(x)||!Number.isFinite(p))return "";const saved=x*p/100;return (x-saved).toLocaleString(undefined,{maximumFractionDigits:2})},[price,percent]);
  const vat=useMemo(()=>{const x=Number(price),r=Number(vatRate);if(!price||!Number.isFinite(x)||!Number.isFinite(r))return null;const v=x*r/100;return {vat:v,total:x+v}},[price,vatRate]);
  const date=useMemo(()=>{if(!start||!end)return "";const s=new Date(start+"T00:00:00"),e=new Date(end+"T00:00:00");const d=Math.round((e.getTime()-s.getTime())/86400000);if(!Number.isFinite(d)||d<0)return "";return String(d+(inclusive?1:0))},[start,end,inclusive]);
  const unitConfigs:Record<string,{units:{id:string;label:string}[];convert:(v:number,u:string)=>number}>={length:{units:[{id:"mm",label:ko?"밀리미터 (mm)":"Millimeter (mm)"},{id:"cm",label:ko?"센티미터 (cm)":"Centimeter (cm)"},{id:"m",label:ko?"미터 (m)":"Meter (m)"},{id:"km",label:ko?"킬로미터 (km)":"Kilometer (km)"},{id:"in",label:ko?"인치 (in)":"Inch (in)"},{id:"ft",label:ko?"피트 (ft)":"Foot (ft)"},{id:"yd",label:ko?"야드 (yd)":"Yard (yd)"},{id:"mi",label:ko?"마일 (mi)":"Mile (mi)"}],convert:(v,u)=>v*({mm:.001,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mi:1609.344}[u]??1)},weight:{units:[{id:"mg",label:ko?"밀리그램 (mg)":"Milligram (mg)"},{id:"g",label:ko?"그램 (g)":"Gram (g)"},{id:"kg",label:ko?"킬로그램 (kg)":"Kilogram (kg)"},{id:"t",label:ko?"톤 (t)":"Metric ton (t)"},{id:"oz",label:ko?"온스 (oz)":"Ounce (oz)"},{id:"lb",label:ko?"파운드 (lb)":"Pound (lb)"}],convert:(v,u)=>v*({mg:.000001,g:.001,kg:1,t:1000,oz:.028349523125,lb:.45359237}[u]??1)},area:{units:[{id:"cm2",label:ko?"제곱센티미터 (cm²)":"Square centimeter (cm²)"},{id:"m2",label:ko?"제곱미터 (m²)":"Square meter (m²)"},{id:"km2",label:ko?"제곱킬로미터 (km²)":"Square kilometer (km²)"},{id:"pyeong",label:ko?"평":"Pyeong"},{id:"ft2",label:ko?"제곱피트 (ft²)":"Square foot (ft²)"},{id:"acre",label:ko?"에이커 (acre)":"Acre (acre)"}],convert:(v,u)=>v*({cm2:.0001,m2:1,km2:1000000,pyeong:3.305785,ft2:.09290304,acre:4046.8564224}[u]??1)},volume:{units:[{id:"ml",label:ko?"밀리리터 (mL)":"Milliliter (mL)"},{id:"l",label:ko?"리터 (L)":"Liter (L)"},{id:"m3",label:ko?"세제곱미터 (m³)":"Cubic meter (m³)"},{id:"cc",label:ko?"세제곱센티미터 (cc)":"Cubic centimeter (cc)"},{id:"gal",label:ko?"갤런 (gal)":"Gallon (gal)"},{id:"cup",label:ko?"컵 (cup)":"Cup (cup)"}],convert:(v,u)=>v*({ml:.001,l:1,m3:1000,cc:.001,gal:3.785411784,cup:.2365882365}[u]??1)},temperature:{units:[{id:"c",label:ko?"섭씨 (°C)":"Celsius (°C)"},{id:"f",label:ko?"화씨 (°F)":"Fahrenheit (°F)"},{id:"k",label:ko?"켈빈 (K)":"Kelvin (K)"}],convert:(v,u)=>u==="f"?(v-32)*5/9:u==="k"?v-273.15:v},data:{units:[{id:"b",label:ko?"바이트 (B)":"Byte (B)"},{id:"kb",label:ko?"킬로바이트 (KB)":"Kilobyte (KB)"},{id:"mb",label:ko?"메가바이트 (MB)":"Megabyte (MB)"},{id:"gb",label:ko?"기가바이트 (GB)":"Gigabyte (GB)"},{id:"tb",label:ko?"테라바이트 (TB)":"Terabyte (TB)"}],convert:(v,u)=>v*({b:1,kb:1024,mb:1024**2,gb:1024**3,tb:1024**4}[u]??1)}}; 
const unitResults=useMemo(()=>{const x=Number(unitValue),cfg=unitConfigs[unitCategory];if(!unitValue||!Number.isFinite(x)||!cfg)return [];const base=cfg.convert(x,unit);const toValue=(id:string)=>unitCategory==="temperature"?(id==="c"?base:id==="f"?base*9/5+32:base+273.15):base/(unitConfigs[unitCategory].convert(1,id));return cfg.units.map(item=>`${item.label}: ${Number(toValue(item.id)).toLocaleString(undefined,{maximumFractionDigits:10})}`)},[unitValue,unit,unitCategory]);
  const ratio=useMemo(()=>{const x=Number(ratioA),y=Number(ratioB),z=Number(ratioC);if(!ratioA||!ratioB||!ratioC||!y)return "";return (x/y*z).toLocaleString(undefined,{maximumFractionDigits:10})},[ratioA,ratioB,ratioC]);
  const change=useMemo(()=>{const x=Number(before),y=Number(after);if(!before||!after||!Number.isFinite(x)||!Number.isFinite(y)||x===0)return "";return `${((y-x)/Math.abs(x)*100).toLocaleString(undefined,{maximumFractionDigits:2})}%`},[before,after]);
  const margin=useMemo(()=>{const c=Number(cost),s=Number(sale);if(!cost||!sale||!Number.isFinite(c)||!Number.isFinite(s)||s===0)return null;return {profit:s-c,margin:(s-c)/s*100,markup:(s-c)/c*100}},[cost,sale]);
  const loanResult=useMemo(()=>{const p=Number(loan),r=Number(loanRate)/100/12,n=Number(loanYears)*12;if(!loan||!loanRate||!loanYears||p<=0||r<0||n<=0)return null;const payment=r===0?p/n:p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);return {payment,total:payment*n,interest:payment*n-p}},[loan,loanRate,loanYears]);
  const installmentResult=useMemo(()=>{const p=Number(installment),r=Number(installmentRate)/100/12,n=Number(installmentMonths);if(!installment||p<=0||r<0||n<=0)return null;const payment=r===0?p/n:p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);return {payment,total:payment*n,interest:payment*n-p}},[installment,installmentRate,installmentMonths]);
  const timeResult=useMemo(()=>{if(!timeStart||!timeEnd)return null;const [sh,sm]=timeStart.split(":").map(Number),[eh,em]=timeEnd.split(":").map(Number);if(!Number.isFinite(sh)||!Number.isFinite(sm)||!Number.isFinite(eh)||!Number.isFinite(em))return null;let start=sh*60+sm,end=eh*60+em;if(end<start)end+=24*60;const breakTime=Math.max(0,Number(breakMinutes)||0);const total=Math.max(0,end-start-breakTime);return {hours:Math.floor(total/60),minutes:total%60,total}},[timeStart,timeEnd,breakMinutes]);
  const reset=()=>{setA("");setB("");setPercent("");setPrice("");setStart("");setEnd("");setUnitValue("");setRatioA("");setRatioB("");setRatioC("");setBefore("");setAfter("");setCost("");setSale("");setLoan("");setInstallment("");setTimeStart("");setTimeEnd("");setBreakMinutes("0")};
  const tools=[["basic",Calculator,ko?"일반 계산":"Basic"],["percent",Percent,ko?"퍼센트":"Percent"],["discount",Receipt,ko?"할인":"Discount"],["vat",Receipt,ko?"부가세":"VAT"],["date",CalendarDays,ko?"날짜·기간":"Date"],["unit",Ruler,ko?"단위":"Units"],["ratio",Scale,ko?"비율":"Ratio"],["change",TrendingUp,ko?"증감률":"Change"],["margin",Receipt,ko?"마진":"Margin"],["loan",Calculator,ko?"대출 이자":"Loan"],["installment",Receipt,ko?"할부":"Installment"],["time",CalendarDays,ko?"시간":"Time"]] as const;
  const field="w-full min-w-0 rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100";
  const result=(value:string,label:string,suffix="")=><div className="rounded-xl bg-blue-50 p-4"><div className="text-xs font-semibold text-blue-600">{label}</div><div className="mt-1 min-h-6 break-words text-lg font-bold text-gray-800">{value?value+(suffix?" "+suffix:""):"—"}</div></div>;

  return <section className="rounded-2xl border border-white/60 bg-white/80 p-4 shadow-md backdrop-blur-sm sm:p-5">
    <div className="mb-4 flex items-center gap-2"><Calculator className="h-5 w-5 text-blue-600"/><div><h2 className="text-lg font-bold text-gray-800">{ko?"복합 계산기":"Compound Calculator"}</h2><p className="text-xs text-gray-500">{ko?"자주 사용하는 계산을 한곳에서 빠르게 처리하세요.":"Common calculations in one place."}</p></div></div>
    <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{tools.map(([id,Icon,label])=><button key={id} type="button" onClick={()=>{setMode(id);reset()}} className={`flex min-h-11 items-center justify-center gap-1.5 rounded-xl px-2 py-2.5 text-xs font-bold sm:text-sm ${mode===id?"bg-gradient-to-r from-blue-600 to-sky-500 text-white shadow-sm":"bg-white text-gray-600 hover:bg-blue-50"}`}><Icon className="h-4 w-4 shrink-0"/>{label}</button>)}</div>

    {mode==="basic"&&<div className="space-y-3"><div className="grid grid-cols-[minmax(0,1fr)_4rem_minmax(0,1fr)] gap-2"><input className={field} inputMode="decimal" value={a} onChange={e=>setA(e.target.value)} placeholder={ko?"첫 번째 숫자":"First number"}/><select className={field+" px-2"} value={op} onChange={e=>setOp(e.target.value)}><option>+</option><option>-</option><option>×</option><option>÷</option><option>%</option><option>^</option></select><input className={field} inputMode="decimal" value={b} onChange={e=>setB(e.target.value)} placeholder={ko?"두 번째 숫자":"Second number"}/></div>{result(basic,ko?"계산 결과":"Result")}</div>}
    {mode==="percent"&&<div className="space-y-3"><input className={field} inputMode="decimal" value={a} onChange={e=>setA(e.target.value)} placeholder={ko?"기준 금액 또는 숫자":"Base amount or number"}/><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2"><input className={field} inputMode="decimal" value={percent} onChange={e=>setPercent(e.target.value)} placeholder={ko?"퍼센트":"Percent"}/><b>%</b></div>{result(percentResult,ko?"계산 결과":"Result")}</div>}
    {mode==="discount"&&<div className="space-y-3"><input className={field} inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder={ko?"원래 가격 (원)":"Original price (KRW)"}/><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2"><input className={field} inputMode="decimal" value={percent} onChange={e=>setPercent(e.target.value)} placeholder={ko?"할인율":"Discount rate"}/><b>%</b></div>{result(discount,ko?"할인 후 가격":"Price after discount",ko?"원":"")}</div>}
    {mode==="vat"&&<div className="space-y-3"><input className={field} inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder={ko?"공급가액 (원)":"Net amount (KRW)"}/><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2"><input className={field} inputMode="decimal" value={vatRate} onChange={e=>setVatRate(e.target.value)}/><b>%</b></div>{vat&&<div className="rounded-xl bg-blue-50 p-4 text-sm"><p>{ko?"부가세":"VAT"} <strong>{vat.vat.toLocaleString()}원</strong></p><p className="mt-1">{ko?"합계":"Total"} <strong>{vat.total.toLocaleString()}원</strong></p></div>}</div>}
    {mode==="date"&&<div className="space-y-3"><label className="block text-xs font-semibold text-gray-600">{ko?"시작일":"Start date"}<input type="date" className={field+" mt-1"} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="block text-xs font-semibold text-gray-600">{ko?"종료일":"End date"}<input type="date" className={field+" mt-1"} value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="flex items-center gap-2 text-sm text-gray-600"><input type="checkbox" checked={inclusive} onChange={e=>setInclusive(e.target.checked)}/>{ko?"시작일·종료일을 모두 포함":"Include both start and end dates"}</label>{result(date,ko?"기간":"Period",date?(ko?"일":"days"):"")}</div>}
    {mode==="unit"&&<div className="space-y-3"><div className="grid grid-cols-2 gap-2"><label className="block text-xs font-semibold text-gray-600">{ko?"단위 종류":"Unit type"}<select className={field+" mt-1"} value={unitCategory} onChange={e=>{setUnitCategory(e.target.value);setUnit(e.target.value==="length"?"m":e.target.value==="weight"?"kg":e.target.value==="area"?"m2":e.target.value==="volume"?"l":e.target.value==="temperature"?"c":"mb")}}><option value="length">{ko?"길이":"Length"}</option><option value="weight">{ko?"무게":"Weight"}</option><option value="area">{ko?"넓이":"Area"}</option><option value="volume">{ko?"부피":"Volume"}</option><option value="temperature">{ko?"온도":"Temperature"}</option><option value="data">{ko?"데이터 용량":"Data size"}</option></select></label><label className="block text-xs font-semibold text-gray-600">{ko?"입력 단위":"Input unit"}<select className={field+" mt-1"} value={unit} onChange={e=>setUnit(e.target.value)}>{unitConfigs[unitCategory].units.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><input className={field} inputMode="decimal" value={unitValue} onChange={e=>setUnitValue(e.target.value)} placeholder={ko?"변환할 숫자 입력":"Enter value"}/>{unitResults.length>0&&unitValue&&<div className="grid grid-cols-1 gap-2 rounded-xl bg-blue-50 p-4 text-sm sm:grid-cols-2">{unitResults.map(x=><div key={x} className="break-words">{x}</div>)}</div>}</div>}
    {mode==="ratio"&&<div className="space-y-3"><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2"><input className={field} inputMode="decimal" value={ratioA} onChange={e=>setRatioA(e.target.value)}/><span>:</span><input className={field} inputMode="decimal" value={ratioB} onChange={e=>setRatioB(e.target.value)}/><span>=</span><input className={field} inputMode="decimal" value={ratioC} onChange={e=>setRatioC(e.target.value)}/></div>{result(ratio,ko?"비례 결과":"Proportional result")}</div>}
    {mode==="change"&&<div className="space-y-3"><input className={field} inputMode="decimal" value={before} onChange={e=>setBefore(e.target.value)} placeholder={ko?"이전 값":"Before"}/><input className={field} inputMode="decimal" value={after} onChange={e=>setAfter(e.target.value)} placeholder={ko?"현재 값":"After"}/>{result(change,ko?"증감률":"Change rate")}</div>}
    {mode==="margin"&&<div className="space-y-3"><input className={field} inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)} placeholder={ko?"원가 (원)":"Cost (KRW)"}/><input className={field} inputMode="decimal" value={sale} onChange={e=>setSale(e.target.value)} placeholder={ko?"판매가 (원)":"Sale price (KRW)"}/>{margin&&<div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"이익":"Profit"}</span><b className="mt-1 block">{margin.profit.toLocaleString()}{ko?"원":"KRW"}</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"이익률":"Margin"}</span><b className="mt-1 block">{margin.margin.toFixed(2)}%</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"마크업":"Markup"}</span><b className="mt-1 block">{margin.markup.toFixed(2)}%</b></div></div>}</div>}
    {mode==="loan"&&<div className="space-y-3"><label className="block text-xs font-semibold text-gray-600">{ko?"대출 원금 (원)":"Loan principal (KRW)"}<input className={field+" mt-1"} inputMode="decimal" value={loan} onChange={e=>setLoan(e.target.value)} placeholder={ko?"예: 10,000,000":"e.g. 10,000,000"}/></label><div className="grid grid-cols-2 gap-2"><label className="block text-xs font-semibold text-gray-600">{ko?"연 이자율 (%)":"Annual interest rate (%)"}<input className={field+" mt-1"} inputMode="decimal" value={loanRate} onChange={e=>setLoanRate(e.target.value)} /></label><label className="block text-xs font-semibold text-gray-600">{ko?"대출 기간 (년)":"Loan term (years)"}<input className={field+" mt-1"} inputMode="numeric" value={loanYears} onChange={e=>setLoanYears(e.target.value)} /></label></div>{loanResult&&<div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"월 상환액":"Monthly payment"}</span><b className="mt-1 block">{loanResult.payment.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"총 이자":"Total interest"}</span><b className="mt-1 block">{loanResult.interest.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"총 상환액":"Total payment"}</span><b className="mt-1 block">{loanResult.total.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div></div>}</div>}
    {mode==="installment"&&<div className="space-y-3"><label className="block text-xs font-semibold text-gray-600">{ko?"할부 원금 (원)":"Installment principal (KRW)"}<input className={field+" mt-1"} inputMode="decimal" value={installment} onChange={e=>setInstallment(e.target.value)} placeholder={ko?"예: 1,200,000":"e.g. 1,200,000"}/></label><div className="grid grid-cols-2 gap-2"><label className="block text-xs font-semibold text-gray-600">{ko?"연 이자율 (%)":"Annual interest rate (%)"}<input className={field+" mt-1"} inputMode="decimal" value={installmentRate} onChange={e=>setInstallmentRate(e.target.value)} /></label><label className="block text-xs font-semibold text-gray-600">{ko?"할부 기간 (개월)":"Installment term (months)"}<input className={field+" mt-1"} inputMode="numeric" value={installmentMonths} onChange={e=>setInstallmentMonths(e.target.value)} /></label></div>{installmentResult&&<div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"월 납입액":"Monthly payment"}</span><b className="mt-1 block">{installmentResult.payment.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"총 이자":"Total interest"}</span><b className="mt-1 block">{installmentResult.interest.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div><div className="rounded-xl bg-blue-50 p-3 text-sm"><span>{ko?"총 납입액":"Total payment"}</span><b className="mt-1 block">{installmentResult.total.toLocaleString(undefined,{maximumFractionDigits:0})}{ko?"원":"KRW"}</b></div></div>}</div>}
    {mode==="time"&&<div className="space-y-3"><div className="grid grid-cols-2 gap-2"><label className="text-xs font-semibold text-gray-600">{ko?"시작 시간":"Start time"}<input type="time" className={field+" mt-1"} value={timeStart} onChange={e=>setTimeStart(e.target.value)}/></label><label className="text-xs font-semibold text-gray-600">{ko?"종료 시간":"End time"}<input type="time" className={field+" mt-1"} value={timeEnd} onChange={e=>setTimeEnd(e.target.value)}/></label></div><input className={field} inputMode="numeric" value={breakMinutes} onChange={e=>setBreakMinutes(e.target.value)} placeholder={ko?"휴게시간(분)":"Break time (minutes)"}/>{timeResult&&<div className="rounded-xl bg-blue-50 p-4"><div className="text-xs font-semibold text-blue-600">{ko?"실제 경과 시간":"Elapsed time"}</div><div className="mt-1 text-xl font-bold text-gray-800">{timeResult.hours}{ko?"시간 ":"h "}{timeResult.minutes}{ko?"분":"min"}</div></div>}</div>}
    <button type="button" onClick={reset} className="mt-4 w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-50">{ko?"입력 초기화":"Reset"}</button>
  </section>;
}